name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=Nikita-Lysiuk&show_icons=true&theme=transparent&title_color=a78bfa&text_color=8b949e&icon_color=a78bfa
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Top Languages
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=Nikita-Lysiuk&langs_count=8&layout=compact&theme=transparent&title_color=a78bfa&text_color=8b949e&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pin Fluid-Engine
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Nikita-Lysiuk&repo=Fluid-Engine&theme=transparent&title_color=ffffff&text_color=a78bfa&icon_color=a78bfa&description_lines_count=2
          path: profile/pin-Fluid-Engine.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pin Vinyl-Store
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Nikita-Lysiuk&repo=Vinyl-Store&theme=transparent&title_color=a78bfa&text_color=8b949e&icon_color=a78bfa&hide_border=true
          path: profile/pin-Vinyl-Store.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pin Egypt-Adventure
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Nikita-Lysiuk&repo=egypt_adventure&theme=transparent&title_color=a78bfa&text_color=8b949e&icon_color=a78bfa&hide_border=true
          path: profile/pin-egypt_adventure.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pin PixelPatternsAI
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Nikita-Lysiuk&repo=PixelPatternsAI&theme=transparent&title_color=a78bfa&text_color=8b949e&icon_color=a78bfa&hide_border=true
          path: profile/pin-PixelPatternsAI.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pin Spring-Library
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Nikita-Lysiuk&repo=spring-library&theme=transparent&title_color=a78bfa&text_color=8b949e&icon_color=a78bfa&hide_border=true
          path: profile/pin-spring-library.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
